package camunda.flownode;

public enum FlowNodeType {
    USER_TASK,
    SERVICE_TASK,
    EXCLUSIVE_GATEWAY,
    PARALLEL_GATEWAY,
    INCLUSIVE_GATEWAY,
    EVENT_SUB_PROCESS,
    CALL_ACTIVITY,
    SUB_PROCESS,
    END_EVENT,
    START_EVENT,
    INTERMEDIATE_CATCH_EVENT,
    INTERMEDIATE_THROW_EVENT,
    BOUNDARY_EVENT,
    NONE
}
